name: gluon
dependencies:
- python=3.6
- numpy
- scipy
- jupyter=1.0.0
- matplotlib=2.2.2
- pandas=0.23.4
- pillow
- graphviz
- python-graphviz
- scikit-learn
- seaborn
- pip:
  - mxnet==1.5.0
  - tensorflow
  - keras
